server:
  port: 8080

spring:
  application:
    name: taishou-steward
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver    # mysql驱动包
    url: jdbc:mysql://localhost:3306/taishou_steward
    username: root
    password: 123456
    initialSize: 5
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200

  redis:
    database: 0
    host: 39.108.184.0
    port: 6379

mybatis:
  mapperLocations: classpath:mapper/*.xml

log.level: info
log.mybatis.level: debug


pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

